### ISSUE TITLE
pypiに0.4(py3対応バージョン)を登録して欲しいです。

### ISSUE THREAD

**Issue by a2chub** [yoshiori/pit#2]
そろそろ世の中がpy3化してきているので神モジュールのpitをpypiへ登録お願いしますm(_ _)m

**Comment by drillbits** [comment]
:star2:

**Comment by takuan-osho** [comment]
:+1:

**Comment by yoshiori** [comment]
@a2chub 最近の setup_tools の状況とかよくわかってなくて億劫になったりして放置しがちなので、a2chub さんが良ければこのリポジトリと pypi の Collaborators になってもらってお任せしちゃうとか可能ですかね？

**Comment by a2chub** [comment]
頑張ります！

**Comment by yoshiori** [comment]
@a2chub github はコラボレータに登録した〜
pypi も登録したいので pypi のユーザー名教えてもらっていいですか？

**Comment by tokuhirom** [comment]
python3 対応してほしいという要望をあげようと思って見に来たら、去年の4月で頓挫していたことを知りました。

**Comment by yoshiori** [comment]
@tokuhirom github の collaborators 入れたから pypi のユーザー名教えて

**Comment by tokuhirom** [comment]
@yoshiori tokuhirom です!

**Comment by yoshiori** [comment]
@tokuhirom done

![2017-02-22 11 -33-24](https://cloud.githubusercontent.com/assets/78609/23215896/5825725e-f957-11e6-8855-7797a668be18.png)

**Comment by hirose31** [comment]
python3 対応してほしいという要望をあげようと思って見に来たら、一昨年の2月で頓挫していたことを知りました。（pypiのユーザー名は `hirose31` です！）

**Comment by yoshiori** [comment]
![2019-03-20 17-28-26 rsipk](https://user-images.githubusercontent.com/78609/54669793-982dd080-4b35-11e9-9ff4-8894bfb296ca.png)

おねしゃす!!!!

**Comment by hirose31** [comment]
0.4 リリースしました！！！ ✨

**Comment by yoshiori** [comment]
ありがとう！！
